language: python

python:
  - 2.6
  - 2.7

before_install:
 - sudo apt-get remove chromium firefox mongodb-10gen
 - sudo apt-get install texlive
# - sudo apt-add-repository -y ppa:texlive-backports/ppa
# - sudo apt-get update
# - sudo apt-get install texlive

install:
  - "pip install -r requirements.txt"

script:
  - make html && make html
  - make singlehtml && make singlehtml
  - make text
  - make singletext
  - make latex
